name: color_picker
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_material_color_picker: ^1.2.0
  shared_preferences: ^2.2.2
  palette_generator: ^0.3.3+3
  pick_color: ^0.0.4
  unsplash_client: ^2.2.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: SpaceGroteskBold
      fonts:
        - asset: fonts/SpaceGrotesk-Bold.ttf
    - family: SpaceGroteskRegular
      fonts:
        - asset: fonts/SpaceGrotesk-Regular.ttf
  assets:
    - assets/background.jpg